on:
  push:
    branches:
      - main
    paths:
      - 'extensions/*/*.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH

      - run: |
          curl -sLO https://download.clojure.org/install/linux-install-1.11.1.1113.sh
          chmod +x linux-install-1.11.1.1113.sh
          sudo ./linux-install-1.11.1.1113.sh

      - run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          sudo ./install

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git diff --name-status HEAD~1

      - run: clj --version

      - run: bb --version